@startuml Enregistrement_Resultats_Session

left to right direction

skinparam shadowing false
skinparam defaultFontName Helvetica
skinparam actorStyle awesome

rectangle "Application VR" as VR

rectangle "Système d'enregistrement des sessions" {

  usecase "Enregistrer une session\nde formation" as Enregistrer

  usecase "Vérifier les données\nreçues" as Verifier

  usecase "Mettre les données à disposition\npour le suivi et les statistiques" as Suivi

  usecase "Refuser l'enregistrement" as Refuser
  }

rectangle "Backend" {
  usecase "Enregistrer en base\nde données" as EnregistrerDB
}
VR -- Enregistrer

EnregistrerDB .up.> Suivi : <<include>>
Enregistrer ..> Verifier : <<include>>
Enregistrer ..> Suivi : <<include>>
Enregistrer <.. Refuser : <<extend>>

@enduml