@startuml Raffinement_Enregistrement_Session_Formation

left to right direction

skinparam shadowing false
skinparam defaultFontName Helvetica
skinparam actorStyle awesome

rectangle "Application VR" as VR

rectangle "Backend Immersio" {

    usecase "Enregistrer les résultats\nd'une session" as Enregistrer

    usecase "Enregistrer la session" as Stocker

    usecase "mettre les résultats à disposition\n des tableaux de bord" as Recevoir

    
}

VR -- Enregistrer

Enregistrer ..> Stocker : <<include>>
Enregistrer ..> Recevoir : <<include>>


@enduml