@startuml Raffinement_Creation_Employe

left to right direction

skinparam shadowing false
skinparam defaultFontName Helvetica
skinparam actorStyle awesome

actor "Company" as Company

rectangle "Dashboard Company" {

    usecase "Saisir les informations\nde l'employé" as Informations

    usecase "Définir un PIN" as Pin

    usecase "Créer un employé" as Creer

    usecase "Générer automatiquement\nle code d'accès" as Code

    usecase "Enregistrer l'employé" as Enregistrer

    usecase "Afficher le code\nd'accès" as Afficher
}

rectangle "Backend Immersio" {
    usecase "Générer le code" as GenCode
    usecase "Persister l'employé" as Persister
}

Code ..> GenCode : <<include>>
Enregistrer ..> Persister : <<include>>

Company -- Creer
Creer ..> Informations : <<include>>
Creer ..> Pin : <<include>>

Creer ..> Code : <<include>>
Creer ..> Enregistrer : <<include>>
Creer ..> Afficher : <<include>>


@enduml