@startuml UC_Formations

left to right direction

skinparam shadowing false
skinparam defaultFontName Helvetica
skinparam actorStyle awesome

actor "Employé" as Employe

rectangle "Application VR" {

    usecase "Consulter les formations\ndisponibles" as UC1
    usecase "Lancer une formation" as UC2

}

Employe --> UC1
Employe --> UC2

UC2 .> UC1 : <<extend>>

@enduml